### ISSUE TITLE
Make a student profile page

### ISSUE THREAD

**Issue by Genius-Raptor** [Genius-Raptor/PnS-Connect#1]
## What is needed
Once you visit the `/children` page, under each child there is a "View Profile" button. It currently does not do anything. It should lead to a page that will show all of the details of the child.

## How to do it
The button should lead to a `/child` accessed via POST so that a user cannot see other children's detail. It should contain a picture of the child (use matpat.png until this feature is added) and all other data present related to a student in the student table. Mention any changes done in the database, not that there should be any

**Comment by Genius-Raptor** [comment]
Sure @Abirami04M! Ask me if you need any additional information.

**Comment by Abirami04M** [comment]
@Genius-Raptor Will do,thanks!

**Comment by SohamDutta2002** [comment]
Hello @Genius-Raptor , I was looking to contribute to a good first issue and came across this. Can I take it up and work on it?

**Comment by Genius-Raptor** [comment]
@SohamDutta2002 Yes, sure!
