### ISSUE TITLE
Add dark mode throughout the webapp

### ISSUE THREAD

**Issue by Genius-Raptor** [Genius-Raptor/PnS-Connect#2]
## What to do
Once you login, you can see a toggle switch in the top right of the web page. Currently, toggling it will switch the website to dark mode, but the website will switch back to light mode as soon as you load another page. Dark mode should be carried on throughout the webpage.

## How to do it
This can be done entirely on the frontend of the application, but it will not remember a user's preferences. This is acceptable, but anybody is welcome to try to save it on the backend, as long as it does not introduce any security risks.

**Comment by Sachinsingh2002** [comment]
i want to work in this issue, can you assign it to me...

**Comment by Helion-web** [comment]
Hey @Sachinsingh2002  , I think I have a solution for this issue. If you are unable to proceed into this issue , would it be okay if I took over the assignment and submit?

**Comment by Genius-Raptor** [comment]
You don't need to be assigned the issue to work on it. You can just fork the repository, make the necessary changes and submit a pull request. If you're still unsure as to what to do, watch a tutorial or go to [How to contribute](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project).

**Comment by Genius-Raptor** [comment]
Closed because of #3.
