### ISSUE TITLE
Add the ability for a user to add their children

### ISSUE THREAD

**Issue by Genius-Raptor** [Genius-Raptor/PnS-Connect#4]
## What to do
Currently, there is no way for a user to add a new student. It can only be added by manually inserting the student in the database. A user should be able to add a student using a form.

## How to do it
On the `/children` page, a button at the bottom should redirect the user to a new page at `/new`. This page should have a form that asks the user about all of the details of the user:
- It should not ask for the id; it must be auto-generated
- It should ask for a full name and a short name
- It should ask for a gender and map it to the `male` column (1 if male, 0 if female)
- It should ask for a grade and section
- It should ask for a date of birth and a house (1, 2, or 3)
The `parent_id` should correctly map to the `id` of the current user. A `/apology` page should be rendered in case there is a problem. Any and all changes must be updated in the documentation.

**Comment by aparnagudivada** [comment]
Hi @Genius-Raptor , Can I take up this issue?

**Comment by aparnagudivada** [comment]
@Genius-Raptor Do I need to use the Bootstrap or Can I use the normal CSS as well..

**Comment by Genius-Raptor** [comment]
@aparnagudivada, yes you can take this issue. While it is recommended that you use bootstrap to keep the UI as identical as possible, you can still use your own CSS as long as the UI is similar to the rest of the site. And don't forget to star the repo!

**Comment by aparnagudivada** [comment]
okay will do that

**Comment by aparnagudivada** [comment]
Hi @Genius-Raptor , will design be ok 
<img width="534" alt="design" src="https://github.com/user-attachments/assets/6f8b6d00-2917-4d67-b039-283801f97c5c">

And I just want to know do I need to add the functionality of the "see profile" button on the children page which is in children.html

**Comment by Genius-Raptor** [comment]
Closed due to #5.
